# Generated by Django 4.1.6 on 2023-02-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('paid_to', models.DateField(verbose_name='Оплачено до:')),
                ('orders_paid', models.IntegerField(verbose_name='Оплаченных заказов осталось')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО разработчика')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон')),
                ('telegram', models.CharField(max_length=200, verbose_name='Телеграм')),
                ('access_to_orders', models.BooleanField(verbose_name='Есть ли доступ к заказам')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО менеджера')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон')),
                ('telegram', models.CharField(max_length=200, verbose_name='Телеграм')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО пользователя')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон')),
                ('telegram', models.CharField(max_length=200, verbose_name='Телеграм')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название тарифа')),
                ('max_requests', models.IntegerField(verbose_name='Максимальное кол-во обращений в месяц')),
                ('max_time_for_ansver', models.TimeField(verbose_name='Максимальное время ответа на заявку')),
                ('booking_the_developer', models.BooleanField(verbose_name='Возможность закрепить Подрядчика')),
                ('developer_contact', models.BooleanField(verbose_name='Возможность получить контакты Подрядчика')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО пользователя')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон')),
                ('telegram', models.CharField(max_length=200, verbose_name='Телеграм')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tgbot.company')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание заказа')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='Время получения заказ')),
                ('answer_time', models.DateTimeField(verbose_name='Время ответа на заказ')),
                ('complet', models.BooleanField(verbose_name='Выполнен ли заказ')),
                ('comleted_time', models.DateTimeField(verbose_name='Время выполнения')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tgbot.developer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tgbot.user')),
            ],
        ),
        migrations.CreateModel(
            name='Conversions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='tgbot.developer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='tgbot.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='tgbot.user')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tgbot.tariff'),
        ),
    ]
