# Generated by Django 4.1.6 on 2023-02-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_remove_order_complet_order_status'),
        ('tgbot', '0003_remove_user_telegram_id_developer_state_and_more'),
    ]

    operations = [
    ]
