# Generated by Django 4.1.6 on 2023-02-18 07:34

from django.db import migrations
import datetime


def add_tariff(apps, schema_editor):
    tariffs_in_db = apps.get_model('tgbot', 'Tariff')
    tariffs = [{'title': 'Эконом', 'max_requests': 5, 'max_time_for_ansver': datetime.time(23, 59, 59),
                'booking_the_developer': False, 'developer_contact': False},
               {'title': 'Стандарт', 'max_requests': 15, 'max_time_for_ansver': datetime.time(1),
                'booking_the_developer': True, 'developer_contact': False},
               {'title': 'VIP', 'max_requests': 60, 'max_time_for_ansver': datetime.time(1),
                'booking_the_developer': True, 'developer_contact': True}]

    for tariff in tariffs:
        if tariffs_in_db.objects.filter(title=tariff['title']):
            continue
        else:
            try:
                tariffs_in_db.objects.create(title=tariff['title'], max_requests=tariff['max_requests'],
                                             max_time_for_ansver=tariff['max_time_for_ansver'],
                                             booking_the_developer=tariff['booking_the_developer'],
                                             developer_contact=tariff['developer_contact'])
            except:
                continue


class Migration(migrations.Migration):
    dependencies = [
        ('tgbot', '0005_company_unp'),
    ]

    operations = [
        migrations.RunPython(add_tariff),
    ]
