# Generated by Django 4.1.7 on 2023-02-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_auto_20230218_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='paid_to',
        ),
    ]
