# Generated by Django 4.1.7 on 2023-02-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_alter_company_name_alter_company_orders_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='orders_paid',
            field=models.IntegerField(default=0, verbose_name='Оплаченных заказов осталось'),
        ),
    ]
