# Generated by Django 4.1.6 on 2023-02-18 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0011_alter_company_paid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='paid_to',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Оплачено до:'),
        ),
    ]
