# Generated by Django 4.1.6 on 2023-02-18 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0012_alter_company_paid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='paid_to',
            field=models.DateField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0), null=True, verbose_name='Оплачено до:'),
        ),
    ]
