# Generated by Django 4.1.6 on 2023-02-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0013_alter_company_paid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, default='Какая-то комания', max_length=200, null=True, verbose_name='Название компании'),
        ),
    ]
