# Generated by Django 4.1.6 on 2023-02-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0014_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Цена:'),
            preserve_default=False,
        ),
    ]
